name: build android
on:
  push: {tags:  ['v*']} #  Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

env:
  BUILD_NAME: onsyuri_android

jobs:
  build_android:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
   
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: build onsyuri_android
      env:
        SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
        SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
        SIGN_STORE_PASS: ${{ secrets.SIGN_STORE_PASS }}
      run: cd script && bash ./cross_android.sh

    - name: prepare to release
      run: cp ./build_android/outputs/apk/release/*.apk ${{ env.BUILD_NAME }}.apk
    
    - name: create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.BUILD_NAME }}.apk"
        allowUpdates: "true"
        token: ${{ secrets.GITHUB_TOKEN }}